# -*- coding: utf-8 -*-
"""DL_Lab(04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIKy6Pwm9O3qsyRYNFFdjIPUZuN7V5s6
"""

# Import necessary libraries
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# Sample training data: simple sentences and corresponding labels (1 = positive, 0 = negative)
sentences = [
    "I love this product",
    "This is an amazing movie",
    "I am very happy with the service",
    "The food was delicious",
    "I really enjoyed this experience",
    "Fantastic performance by the actor",
    "The product quality is excellent",
    "I am extremely satisfied",
    "This is the best thing ever",
    "Wonderful and शानदार service",
    "Absolutely loved it",
    "Great experience overall",
    "Very nice and impressive",
    "Superb quality and design",
    "Highly recommend this",
    "I am delighted with this",
    "Everything was perfect",
    "Brilliant work",
    "I liked it a lot",
    "Awesome product",
    "Very good service",
    "This made me happy",
    "Excellent customer support",
    "Totally worth the money",
    "I will buy this again",
    "Pleasant experience",
    "Very comfortable and nice",
    "Top notch quality",
    "Five star experience",
    "Loved the taste",
    "This is the worst experience",
    "I hate this",
    "I am not satisfied",
    "The product is very bad",
    "Terrible service and rude staff",
    "I am very disappointed",
    "This was a waste of money",
    "The food was awful",
    "I will never buy this again",
    "Very poor quality product",
    "Completely useless item",
    "Bad experience overall",
    "Very disappointing service",
    "Worst product ever",
    "I regret buying this",
    "Not worth the money",
    "Extremely bad quality",
    "Horrible experience",
    "I did not like it",
    "Service was very slow",
    "Unhappy with the purchase",
    "It broke very quickly",
    "Very cheap quality",
    "Not good at all",
    "Worst customer support",
    "I am frustrated",
    "Poor packaging",
    "Terrible taste",
    "Very bad experience",
    "Never recommend this"
]

labels =np.array([
    1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,

    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0
])

# Step 1: Tokenize the text
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

# Step 2: Padding the sequences to have the same length
maxlen = 10  # Maximum length of a sentence
X = pad_sequences(sequences, maxlen=maxlen)

# Step 3: Building the RNN model
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=32, input_length=maxlen))

model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

# Step 4: Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Step 5: Train the model
model.fit(X, labels, epochs=20, batch_size=2)

# Step 6: Testing the model on a new sentence
test_sentence = ["This experience"]
test_seq = tokenizer.texts_to_sequences(test_sentence)
test_padded = pad_sequences(test_seq, maxlen=maxlen)
prediction = model.predict(test_padded)

print("Sentiment (0 = Negative, 1 = Positive):", prediction[0][0])